version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'latest'
    open-pull-requests-limit: 30
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Shanghai'
      time: '09:00'

  - package-ecosystem: 'gradle'
    directory: '/'
    target-branch: 'latest'
    open-pull-requests-limit: 30
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Shanghai'
      time: '09:00'
